networks:
    default:
        ipam:
            config: 
                - subnet: 10.0.0.0/24
                  gateway: 10.0.0.1

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
            target: server
            args:
                TZ: ${TZ}
        depends_on:
            - db
        ports:
            - 7171:7171
            - 7172:7172
        tty: true
        # entrypoint: [ "/usr/bin/tfs" ]
        networks:
            default:
                ipv4_address: 10.0.0.2
        volumes:
            - ./data:/home/server/data
            - ./mods:/home/server/mods
            - ./config.lua:/home/server/config.lua
            - ./noticias.txt:/home/server/noticias.txt
    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - db
        image: phpmyadmin:5.2.1-apache
        networks:
            default:
                ipv4_address: 10.0.0.3
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${DB_PORT}
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8080:80
    db:
        container_name: mariadb
        image: mariadb:11.6.2-noble
        networks:
            default:
                ipv4_address: 10.0.0.4
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./schemas/war_cast_mysql.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: true
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
